[package]
name = "serde_nix"
version = "0.1.0"
edition = "2021"

[lib]
path = "./lib.rs"

[dependencies]
thiserror = "2.0.12"
serde = { version = "1.0.218" }
tvix-serde = { git = "https://github.com/tvlfyi/tvix", package = "tvix-serde" }
